### ISSUE TITLE
Update makammusicbrainz version

### ISSUE THREAD

**Issue by philtgun** [sertansenturk/symbtrdataextractor#28] opened 2018-03-23 15:54 UTC
Update dependency `makammusicbrainz` version from 1.3.0 to 1.4.1 to avoid errors while installing requirements:

```
  Could not find a version that satisfies the requirement eyeD3==0.7.9 (from makammusicbrainz->-r requirements (line 3)) (from versions: 0.7.11, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4)
No matching distribution found for eyeD3==0.7.9 (from makammusicbrainz->-r requirements (line 3))
```

**Comment by sertansenturk** [comment] 2018-04-10 00:25
Thank you Philip for informing me of the problem. I'll check the problem over the weekend.

In the meantime could you kindly tell me how you were installing the requirements (`pip install -r requirements`?) and your operating system? The [Travis CI](https://travis-ci.org/sertansenturk/symbtrdataextractor) build is able to install the requirements. I'd like to reproduce your case.

**Comment by philtgun** [comment] 2018-04-11 12:26
Yes, I used pip to install requirements. My system is Kubuntu 17.10.

The problem has been addressed in this [commit for makammusicbrainz](https://github.com/sertansenturk/makammusicbrainz/commit/2fb52322790a3a8b06fd1b86eaa1d43b0ef3018f), the only thing is that version listed in requirements for this repo is outdated (1.3.0) and doesn't include the fix. Last Travis CI build has been performed on October 2016, and I think if you rerun it now, it will show the error.

**Comment by sertansenturk** [comment] 2018-04-18 01:42
Thanks for the pull request. The build seems not to be working. It's possibly due to a change in musicbrainzngs library. Since the error is not related to the makammusicbrainz package anymore, I have merged the pull request and I'm closing the issue.

I will take care of potential schema change problem later, as soon as I have time. In the meantime, please do not hesitate to write me if you require anything more.

**Closed as completed by sertansenturk** 2018-04-18 01:42 UTC
